#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v25
# autospec commit: 9594167
#
Name     : perl-Data-Float
Version  : 0.015
Release  : 32
URL      : https://cpan.metacpan.org/authors/id/R/RR/RRWO/Data-Float-0.015.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/R/RR/RRWO/Data-Float-0.015.tar.gz
Summary  : 'details of the floating point data type'
Group    : Development/Tools
License  : Artistic-1.0-Perl GPL-1.0+
Requires: perl-Data-Float-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
Data::Float - details of the floating point data type
DESCRIPTION
This module is about the native floating point numerical data type.
A floating point number is one of the types of datum that can appear
in the numeric part of a Perl scalar.  This module supplies constants
describing the native floating point type, classification functions,
and functions to manipulate floating point values at a low level.

%package dev
Summary: dev components for the perl-Data-Float package.
Group: Development
Provides: perl-Data-Float-devel = %{version}-%{release}
Requires: perl-Data-Float = %{version}-%{release}

%description dev
dev components for the perl-Data-Float package.


%package perl
Summary: perl components for the perl-Data-Float package.
Group: Default
Requires: perl-Data-Float = %{version}-%{release}

%description perl
perl components for the perl-Data-Float package.


%prep
%setup -q -n Data-Float-0.015
cd %{_builddir}/Data-Float-0.015

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Data::Float.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
